---

- hosts: all
  become: yes

  tasks:
   - name: Gather all legacy facts of routers
     ios_facts:
       gather_subset: all

   - name: Show ansible_net_all_ipv4_addresses fact
     debug: var=ansible_net_all_ipv4_addresses

   - name: Show ansible_net_interfaces fact
     debug: var=ansible_net_interfaces['Ethernet0/0']